feat/main-page
8of8player/airbnb-demo-frontend pull request #1
Opened 2018-01-06 01:21 UTC by 8of8player

Версия для десктопа. Есть элементы с заданными высотой/шириной – фикшу.

2018-01-06 14:55 UTC, evgenyrodionov commented
Почему коммиты от другого аккаунта?

2018-01-06 15:03 UTC, imevro requested changes

2018-01-06 15:03 UTC, evgenyrodionov commented on package.json
> +  "name": "demo",
втф? зачем поменял?

2018-01-06 15:03 UTC, evgenyrodionov commented on src/App.js
> +  width: 1124px;
если есть сетка, зачем ты этим сам занимаешься?

2018-01-06 15:03 UTC, evgenyrodionov commented on src/Bottom/index.js
> +import React from "react";
футер = боттом? странный нейминг

2018-01-06 15:03 UTC, evgenyrodionov commented on src/Bottom/index.js
> +import Twitter from "./twitter.png";
свг

2018-01-06 15:03 UTC, evgenyrodionov commented on src/Bottom/index.js
> +import { CircularBold, CircularBook, CircularLight } from "../styled";
а зачем ты так сделал?

2018-01-06 15:03 UTC, evgenyrodionov commented on src/Bottom/index.js
> +import { Flex, Image, Link } from "../styled";
как понять что такое флекс?

2018-01-06 15:03 UTC, evgenyrodionov commented on src/Bottom/index.js
> +import Twitter from "./twitter.png";
и нейминг как у компонентов, хотя это файлы

2018-01-06 15:03 UTC, evgenyrodionov commented on src/ButtonNext.js
> +  background: url(http://i.imgur.com/7fqRgbK.png);
хуевый выбор

2018-01-06 15:03 UTC, evgenyrodionov commented on src/ButtonNext.js
> +  return <Button />;
читай частые ошибки

2018-01-06 15:03 UTC, evgenyrodionov commented on src/Experiences/index.js
> +  left: 1028px;
не проще райт задать? и pos: rel для контейнера, чтобы не пришлось позиционировать относительно экрана

2018-01-06 15:03 UTC, evgenyrodionov commented on src/Experiences/index.js
> +        <Col lg={1}>
зачем тут сетка?

2018-01-06 15:03 UTC, evgenyrodionov commented on src/Experiences/index.js
> +        <Col lg={1}>
конкретно на заголовок

2018-01-06 15:03 UTC, evgenyrodionov commented on src/Explore/index.js
> +const Card = styled.div`
а перейти по ней как на страницу, на которую она ведет?

2018-01-06 15:03 UTC, evgenyrodionov commented on src/Footer/index.js
> +            <Option value="notEnglish"> not English </Option>
лол?

2018-01-06 15:03 UTC, evgenyrodionov commented on src/Footer/index.js
> +          <Point>
это что и зачем?

2018-01-06 15:03 UTC, evgenyrodionov commented on src/Header/index.js
> +          </ValueDouble>
вэльюдабл? в смысле?

2018-01-06 15:03 UTC, evgenyrodionov commented on src/styled.js
> +export const Row = styled.div`
есть же сетка, реакт-флекбокс-грид?

2018-01-06 15:14 UTC, 8of8player commented on package.json
> +  "name": "demo",
+

2018-01-06 15:16 UTC, 8of8player commented on src/Bottom/index.js
> +import { Flex, Image, Link } from "../styled";
√

2018-01-06 15:17 UTC, 8of8player commented on src/Experiences/index.js
> +        <Col lg={1}>
√

2018-01-06 15:17 UTC, 8of8player commented on src/Header/index.js
> +          </ValueDouble>
√

2018-01-06 15:24 UTC, 8of8player commented on src/Bottom/index.js
> +import Twitter from "./twitter.png";
√

2018-01-06 15:28 UTC, 8of8player commented on src/ButtonNext.js
> +  return <Button />;
√

2018-01-06 15:28 UTC, 8of8player commented on src/Footer/index.js
> +            <Option value="notEnglish"> not English </Option>
√

2018-01-06 17:02 UTC, 8of8player commented on src/Explore/index.js
> +const Card = styled.div`
Оставил Card div'ом, т.к если сделать ссылкой, то бордер на мобиле ставит неверно.

2018-01-06 20:34 UTC, 8of8player commented
Настроен адаптив.

Что не успел пофиксить: 
1. При использовании Grid плывет мобильная версия, оставил свой кастомный контейнер
2. Bottom – отдельный от футера компонент (с макетом все совпадает)

Есть несколько костылей, ибо не умею пока в пропсы и прочее.

2018-01-07 17:38 UTC, imevro requested changes

2018-01-07 17:38 UTC, evgenyrodionov commented on src/App.js
> +  ${"" /* margin-left: auto;
мусор выноси

2018-01-07 17:38 UTC, evgenyrodionov commented on src/Bottom/index.js
> +const Rule = P.extend`
че за руль и почему эти стили не могут быть на ссылке

2018-01-07 17:38 UTC, evgenyrodionov commented on src/Explore/index.js
> +const Card = styled.div`
ну так исправь это

2018-01-07 17:38 UTC, evgenyrodionov commented on src/Footer/index.js
> +            <ColumnSection>
зачем эти обертки?

2018-01-07 17:38 UTC, evgenyrodionov commented on src/Footer/index.js
> +          <Column>
http://htmlreference.io/element/nav/

2018-01-07 17:38 UTC, evgenyrodionov commented on src/styled.js
> +export const DivFlex = styled.div`
дивфлекс бля ну и нейминг

2018-01-08 23:50 UTC, merged